### ISSUE TITLE
Memgraph can't start with volume in bind mode

### ISSUE THREAD

**Issue by vector-mj** [memgraph/memgraph#1734]
**Memgraph version**: v2.14.1

**Log**:
```sh
[2024-02-18 18:14:30.083] [warning] storage_parallel_index_recovery flag is deprecated. Check storage_mode_parallel_schema_recovery for more details.
[2024-02-18 18:14:30.083] [warning] storage_parallel_index_recovery flag is deprecated. Check storage_mode_parallel_schema_recovery for more details.
You are running Memgraph v2.14.1
To get started with Memgraph, visit https://memgr.ph/start
```
**Environment**
```sh
--log-level=TRACE
```

**My docker-compose file**
```yaml
version: '3.7'
services:
  memgraph:
    image: memgraph/memgraph
    ports:
      - 7687
      - 7444
      - 3000:3000
    command: ["--log-level=TRACE"]
    volumes:
      - ./data:/var/lib/memgraph
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
```

**Description**
Memgraph can't start and doesn't have any output log even in the TRACE log level, but it works correctly if I change the bind type volume to docker volume.

**Comment by katarinasupe** [comment]
Hi @vector-mj, thank you for opening the issue. We know this is not working, probably due to file ownership issues. Is this a blocker for you currently or is the Docker volume workaround good enough for you for now?

**Comment by katarinasupe** [comment]
So far, we recommended changing the default location of a docker data directory with the `--data-root` [property](https://docs.docker.com/engine/reference/commandline/dockerd/ ). Here is more on that topic: 
https://stackoverflow.com/questions/36014554/how-to-change-the-default-location-for-docker-create-volume-command

Let me know if that helps somehow.

We also had suggestions from our Discord community for workarounds ([you can join there](https://www.discord.gg/memgraph)). For example, this is what a community member suggested for the Memgraph Platform (which can probably be applied to Memgraph image as well):
```
version: "3.9"
services:
  memgraph:
    image: memgraph/memgraph-platform:latest
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib
      - mg_log:/var/log
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH="--storage-properties-on-edges=true --log-level=TRACE"
    entrypoint: ["/usr/bin/supervisord"]
volumes:
  mg_lib:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'path/on/host'
  mg_log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'path/on/host'
  mg_etc:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'path/on/host'
```

Tbh, I haven't tried the above, and it should be tested, but I thought it's best I provide you with all the information I have. Here is the [thread on Discord](https://discord.com/channels/842007348272169002/1076084990191874069/1166696944358395995).

**Comment by vector-mj** [comment]
Thank you @katarinasupe, your Docker compose manifest worked for me.

```yaml
version: '3.9'
services:
  memgraph:
    image: docker.arvancloud.ir/memgraph/memgraph-platform
    container_name: memgraph
    ports:
      - 7687:7687
      - 7444:7444
      - 3000:3000
    environment:
      MEMGRAPH: "--memory-limit=1000 --log-level=TRACE --storage-properties-on-edges=true --storage-snapshot-interval-sec=2 --storage-snapshot-retention-count=3 --storage-mode=ON_DISK_TRANSACTIONAL --storage-snapshot-on-exit=true"
    volumes:
      - mg_lib:/var/lib
      - mg_log:/var/log
      - mg_etc:/etc/memgraph
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
volumes:
  mg_lib:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './memgraph/data'
  mg_log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './memgraph/log'
  mg_etc:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './memgraph/config'
```
