### ISSUE TITLE
memgraph in Openshift crashing

### ISSUE THREAD

**Issue by vojtechkorec67** [memgraph/memgraph#2192]
**Memgraph version**
1.18-memgraph-2.18

**Environment**
Running on OpenShift, using the Docker image 'central-docker-release.artif.apps.corp/memgraph/memgraph-mage:1.18-memgraph-2.18'. 

**Describe the bug**
Memgraph crashes upon startup. The container of the pod ends with return code 139.

**Expected behavior**
Memgraph should start without crashing.

**Logs**
Jul 10 11:22:16 occ01bm04.infra.cc.corp systemd[1]: Started Process Core Dump (PID 3251944/UID 0).
Jul 10 11:22:17 occ01bm04.infra.cc.corp [3252005]: Could not parse number of program headers from core file: invalid `Elf' handle
Jul 10 11:22:17 occ01bm04.infra.cc.corp systemd-coredump[3251945]: [🡕] Process 3251937 (memgraph) of user 1001950000 dumped core.

                                                                   Module /usr/lib/memgraph/memgraph without build-id.
                                                                   Module /usr/lib/memgraph/memgraph
                                                                   Stack trace of thread 62:
                                                                   #0  0x00007fed8c574ce1 n/a (/lib/x86_64-linux-gnu/libc-2.31.so + 0x38ce1)
                                                                   ELF object binary architecture: AMD x86-64
Jul 10 11:22:17 occ01bm04.infra.cc.corp systemd[1]: [systemd-coredump@108-3251944-0.service](mailto:systemd-coredump@108-3251944-0.service): Deactivated successfully.
Jul 10 11:22:17 occ01bm04.infra.cc.corp systemd[1]: [systemd-coredump@108-3251944-0.service](mailto:systemd-coredump@108-3251944-0.service): Consumed 1.245s CPU time.

**Comment by gitbuda** [comment]
Openshift related issues are #1440 and #1457

**Comment by katarinasupe** [comment]
Hi @vojtechkorec67, thank you for reporting this 🙏 Do you have an option to run Memgraph in a different way or is this the only option for you? Are you blocked by this issue?

**Comment by vojtechkorec67** [comment]
Hello,

Unfortunately, this problem is currently blocking us, as we intended to use
the memgraph database in Openshift at our company.
Did you manage to replicate the error? Any idea how long it might take to
resolve the issue?

Thank you very much

Vojtěch Korec

po 15. 7. 2024 v 9:19 odesílatel Katarina Supe ***@***.***>
napsal:

**Comment by katarinasupe** [comment]
Hi @vojtechkorec67, we are prioritizing the work on the product based on where the feature requests are coming from and how important it is for the product. Currently, this issue is under community issues, meaning it will be handled based on the prioritization system within that project. Since there haven't been many community issues regarding OpenShift, I can't tell you how long it will take to resolve the issue. I will bump up the severity to note you're blocked.

You mentioned using Memgraph within your company, so I suggest we [hop on a call](https://memgraph.com/office-hours) to discuss your plans and to see if we can push this sooner based on your plans with Memgraph.

@gitbuda, feel free to add anything else you know since you added a comment here.

**Comment by katarinasupe** [comment]
hi @vojtechkorec67! We discussed this issue with your colleague Jiri on the call. If you can, could you share more information about your Openshift environment? Are there any specific settings that might impact Memgraph installation?
Also, are you using Memgraph image from Docker Hub or did you build something specific?

**Comment by hal-eisen-MG** [comment]
Would it be possible to share the operating system and hardware architecture with us? That ELF error often indicates a mismatch between the actual environment and how the Memgraph software was compiled.

**Comment by KORECVOJ** [comment]
hi @katarinasupe , we are using Memgraph image from Docker Hub. I will try to get more information about our Openshift environment from our Openshift provider.
I will let you know as soon as possible.

**Comment by KORECVOJ** [comment]
Hi @hal-eisen-MG , @katarinasupe , im unfortunately not able to share with you informatinon about our openshift enviroment because of corporate policy concernig critical infrastructure. Do you have any recommendations on how to proceed with debugging this problem?

**Comment by DavIvek** [comment]
@KORECVOJ I set up Memgraph with OpenShift locally, and Memgraph is also crashing in my case. I'll try to resolve the issue and inform you about the potential cause.

**Comment by KORECVOJ** [comment]
Hi @DavIvek, thank you very much, appreciate it.

**Comment by DavIvek** [comment]
@KORECVOJ Did you maybe try to set up a memgraph without mage? I'm asking this, so we can distinguish if this is a memgraph or a mage issue.

**Comment by DavIvek** [comment]
@KORECVOJ After accessing the container and running Memgraph with GDB, I discovered that MY problem was in the data directory. After configuring the deployment yaml file to run the pod with correct data dir, Memgraph started working as expected. From your logs I don't think you are experiencing the same issue. 
Can you provide us with more info about your Memgraph config and deployment?

**Comment by KORECVOJ** [comment]
Hi @DavIvek, I have a problem uploading the file to GitHub, so I will share the OpenShift deployment configuration with you this way: 

ind: Deployment
apiVersion: apps/v1
metadata:
  name: memgraph
  namespace: tp-psql-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memgraph
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: memgraph
      annotations:
        openshift.openshift.io/restartedAt: '2024-07-10T10:55:18.054Z'
    spec:
      restartPolicy: Always
      serviceAccountName: memgraph
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 32Gi
            requests:
              cpu: 200m
              memory: 32Gi
          terminationMessagePath: /dev/termination-log
          name: memgraph
          command:
            - /bin/sh
          securityContext:
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 7687
              protocol: TCP
            - containerPort: 7444
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: memgraph-data
              mountPath: /var/lib/memgraph
            - name: memgraph-log
              mountPath: /var/log
            - name: memgraph-conf
              mountPath: /etc/memgraph/memgraph.conf
              subPath: memgraph.conf
          terminationMessagePolicy: File
          image: 'central-docker-release.artif.apps.corp/memgraph/memgraph-mage:1.18-memgraph-2.18'
          args:
            - '-c'
            - sleep 300000
      serviceAccount: memgraph
      volumes:
        - name: memgraph-data
          emptyDir: {}
        - name: memgraph-log
          persistentVolumeClaim:
            claimName: memgraph-log
        - name: memgraph-conf
          configMap:
            name: memgraph-conf
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

**Comment by KORECVOJ** [comment]
Hi @DavIvek, I have a problem uploading the file to GitHub, so I will share the OpenShift deployment configuration with you this way:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: memgraph
  namespace: tp-psql-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memgraph
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: memgraph
      annotations:
        openshift.openshift.io/restartedAt: '2024-07-10T10:55:18.054Z'
    spec:
      restartPolicy: Always
      serviceAccountName: memgraph
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 32Gi
            requests:
              cpu: 200m
              memory: 32Gi
          terminationMessagePath: /dev/termination-log
          name: memgraph
          command:
            - /bin/sh
          securityContext:
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 7687
              protocol: TCP
            - containerPort: 7444
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: memgraph-data
              mountPath: /var/lib/memgraph
            - name: memgraph-log
              mountPath: /var/log
            - name: memgraph-conf
              mountPath: /etc/memgraph/memgraph.conf
              subPath: memgraph.conf
          terminationMessagePolicy: File
          image: 'central-docker-release.artif.apps.corp/memgraph/memgraph-mage:1.18-memgraph-2.18'
          args:
            - '-c'
            - sleep 300000
      serviceAccount: memgraph
      volumes:
        - name: memgraph-data
          emptyDir: {}
        - name: memgraph-log
          persistentVolumeClaim:
            claimName: memgraph-log
        - name: memgraph-conf
          configMap:
            name: memgraph-conf
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

**Comment by KORECVOJ** [comment]
@DavIvek, I was only trying to set up a Memgraph with MAGE.

**Comment by DavIvek** [comment]
@KORECVOJ I apologize for the delay in my response. 

I was able to deploy memgraph with mage using the provided configuration. The only change I made was setting the security context of the container to run as user 0. However, it doesn't seem that your issue is due to that. I believe it is more specific to your use case and may be related to your operating system or hardware.

**Comment by DavIvek** [comment]
You could try using the `relwithdebinfo` docker image (you can find it [here](https://hub.docker.com/r/memgraph/memgraph-mage/tags)) and run a debug pod to debug memgraph with `gdb` (which will be installed inside the container). The memgraph executable will be located in the `/usr/lib/memgraph/` directory.

**Comment by KORECVOJ** [comment]
Hi @DavIvek, I don't have the option in my company to set the security context of the container to run as user 0. Do you think that could cause the CrashLoopBackOff error?

**Comment by DavIvek** [comment]
@KORECVOJ it doesn't look to me that you are experiencing this type of issue from logs you provided.

**Comment by theCamelCaser** [comment]
Hi,
found this issue since I had the same the last days. As far as I could tell by now it was a problem with the user/group context. 

The docker container itself runs in context of user 'memgraph'. So restrictions on the filesystem (even if mapped) are aligned with this user. 

On openshift however, your container runs in the context of a different user/group. In my case this was the user with the id `1002640000`. 
Additionally, it seems that openshift while spinning up pods the link to the mounts will happen as root. So the actual permissions for folders on the volume would be `root:root`. 
What have I done: 

1. I mapped the root folder from my target volume and created 3 folders mg_lib, mg_log, mg_etc and set the chown right away. In my case `memgraph:1002640000`. 
2. Afterwards I added the mounts to the deployment, refering the actual subfolder. 
3. There is an option to change the securityContext in your deplpoyment yaml. This includes runAsUser, runAsGroup, fsGroup. (https://kubernetes.io/docs/tasks/configure-pod-container/security-context/). I changed the runAsGroup and fsGroup to the Openshift id and used the Memgraph UserID as runAsUser.

So in the end the spec part of my config looked like: 

```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appname
        deployment: appname
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.openshift.io/restartedAt: '2025-03-23T20:12:03.345Z'
    spec:
      volumes:
        - name: memgraph
          persistentVolumeClaim:
            claimName: memgraph
      containers:
        - resources:
            limits:
              cpu: 3500m
              memory: 10000Mi
            requests:
              cpu: 500m
              memory: 4000Mi
          terminationMessagePath: /dev/termination-log
          name: appname
          env:
            - name: MEMGRAPH_USER
              value: appname
            - name: MEMGRAPH_PASSWORD
              value: appname-pass
            - name: MG_LOG_LEVEL
              value: TRACE
          ports:
            - name: bolt
              containerPort: 7687
              protocol: TCP
            - name: mglog
              containerPort: 7444
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: memgraph
              mountPath: /var/lib/memgraph
              subPath: mg_lib
            - name: memgraph
              mountPath: /var/log/memgraph
              subPath: mg_log
            - name: memgraph
              mountPath: /etc/memgraph
              subPath: mg_etc
          terminationMessagePolicy: File
          image: 'image-registry.openshift-image-registry.svc:5000/yadayada/appname@sha256:852a253097bbdb7dc5ef2b329f6e6647464b9c118b44d675c4af21971415a8ed'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 100 # USER MEMGRAPH
        runAsGroup: 1002640000
        fsGroup: 1002640000
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

```
