### ISSUE TITLE
No user created with env var leading to no auth required

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#2408]
**Memgraph version**
2.20 (latest)

**Environment**
Docker

**Describe the bug**
User is created via env var MEMGRAPH_USER. Login is allowed to anyone, regardless of username/password. That is not expected behavior based on docs:

> "If the user should authenticate themselves on each session, i.e. provide their password on each session, the part within the brackets is mandatory. Otherwise, the password is set to null, and the user will be allowed to log-in using any password, provided that they use the correct username."

`SHOW USERS` returns empty, although users should have been created. 
`SHOW CURRENT USER` returns `null`.  

**To Reproduce**
Run the following docker compose:
```
services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]
    environment:
      - MEMGRAPH_USER=testuser123
 
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
```

Connect to Memgraph via Memgraph Lab or mgconsole. You'll be able to connect with or without username and have all permissions and see that the current user is always null and there are no users in the database.

**Expected behavior**
I would expect having user test123 created in the database. I would also expect to still have to log in with that user, without password. 

**Logs**
/

**Additional context**
I MEMGRAPH_PASSWORD is defined along with MEMGRAPH_USER, all works as expected. If I create a user once the database is running (with Cypher), all works as expected (I can login only with my username). 

> I have also noticed that it is possible to "brick" your own memgraph by revoking all databases from your user

[This was reported by a community member. ](https://discord.com/channels/842007348272169002/890968055339958292/1293942631465881713)

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Plain memgraph package -> for which Linux?
* Plain memgraph Docker image?
* Which architecture do you use ARM | x86?
* Full Memgraph platform?
