### ISSUE TITLE
Memgraph segfaults on replica restart during write operation on main in k8s 

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#2480]
👋  Hey Memgraph team,  I am observing a scenario where a segfault occurs when replication is enabled. Specifically, in a k8s setup, if there is data being written to the main instance, and the replica pod (registered as a replica using DNS) is deleted and then brought back up, the main pod crashes with exit code 139. I believe what's happening is that the replica DNS is discoverable once the pod itself re-initializes, but the replica memgraph instance hasn't fully started or been considered ready to serve connections yet. 

I can see in my logs that while the replica pod is fully down, the main instance will correctly emit a couldn't replicate data log continuously. But once the replica pod is re-initialized and still in an unhealthy state, the main pod crashes and restarts before the replica instance is healthy and recovers from its snapshot.

This is occuring on the latest memgraph version 2.21.0, using DNS lookup / port 10000, in memory transactional, and with replication-restore-state-on-startup enabled. Let me know if I can provide any other details, thanks!

Context: https://discord.com/channels/842007348272169002/890969266600423504/1306504084563689472

**Comment by antejavor** [comment]
Locally it works: 
```
#!/bin/bash

# Start Memgraph main instance using Docker
docker run -d --name memgraph-main -p 7687:7687 memgraph/memgraph --log-level=TRACE --data-recovery-on-startup=true --replication-restore-state-on-startup=true --also-log-to-stderr

# Wait for the main container to be in running status
echo "Waiting for Memgraph main container to be in running status..."
sleep 10

# Check if the main container is running
MAIN_STATUS=$(docker inspect -f '{{.State.Status}}' memgraph-main)

if [ "$MAIN_STATUS" != "running" ]; then
  echo "Memgraph main container is not running. Please check the Docker logs."
  exit 1
fi

# Start Memgraph replica instance using Docker
docker run -d --name memgraph-replica -p 7688:7687 -p 10000:10000 memgraph/memgraph --log-level=TRACE --data-recovery-on-startup=true --replication-restore-state-on-startup=true --also-log-to-stderr

# Wait for the replica container to be in running status
echo "Waiting for Memgraph replica container to be in running status..."
sleep 10

# Check if the replica container is running
REPLICA_STATUS=$(docker inspect -f '{{.State.Status}}' memgraph-replica)

if [ "$REPLICA_STATUS" != "running" ]; then
  echo "Memgraph replica container is not running. Please check the Docker logs."
  exit 1
fi

# Set the replication role for the replica instance
docker exec -it memgraph-replica bash -c "echo 'SET REPLICATION ROLE TO REPLICA WITH PORT 10000;' | mgconsole"

# Show the replication role for both main and replica instances
docker exec -it memgraph-main bash -c "echo 'SHOW REPLICATION ROLE;' | mgconsole"
docker exec -it memgraph-replica bash -c "echo 'SHOW REPLICATION ROLE;' | mgconsole"

# Get the IP address of the replica container
REPLICA_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' memgraph-replica)

# Register the replica with the main instance
docker exec -it memgraph-main bash -c "echo 'REGISTER REPLICA replica SYNC TO \"$REPLICA_IP:10000\";' | mgconsole"

# Show the replication status for the main instance
docker exec -it memgraph-main bash -c "echo 'SHOW REPLICATION STATUS;' | mgconsole"

# Continuously write data to the main instance
docker exec -d memgraph-main bash -c "while true; do echo 'CREATE (n:Node {name: \"test\"});' | mgconsole; sleep 1; done"

echo "Writing data to the main instance..."

# Wait for a few seconds before restarting the replica container
sleep 5

echo "Restarting the replica container..."
docker restart memgraph-replica

# Wait for the replica container to restart
sleep 3

# Check the status of both main and replica containers
MAIN_STATUS=$(docker inspect -f '{{.State.Status}}' memgraph-main)
REPLICA_STATUS=$(docker inspect -f '{{.State.Status}}' memgraph-replica)

echo "Main instance status: $MAIN_STATUS"
echo "Replica instance status: $REPLICA_STATUS"

# Get the node count from both main and replica instances
MAIN_NODE_COUNT=$(docker exec -it memgraph-main bash -c "echo 'MATCH (n) RETURN count(n);' | mgconsole")
REPLICA_NODE_COUNT=$(docker exec -it memgraph-replica bash -c "echo 'MATCH (n) RETURN count(n);' | mgconsole")

echo "Main instance node count: $MAIN_NODE_COUNT"
echo "Replica instance node count: $REPLICA_NODE_COUNT"

# Display the last 50 lines of logs from both main and replica instances
echo "******** Logs from the main instance: ********"
docker logs memgraph-main --tail=50

echo "******** Logs from the replica instance: ********"
docker logs memgraph-replica --tail=50

# Wait for user input to proceed
read -p "Press Enter to continue..."

# Clean up: stop and remove both main and replica containers
docker stop memgraph-main 
docker stop memgraph-replica
sleep 5
docker rm memgraph-main 
docker rm memgraph-replica

# Delete any dangling Docker volumes created by Memgraph
docker volume rm $(docker volume ls -qf dangling=true)
```

This script passes, will try to replicate in k8s.

**Comment by danielhsu93** [comment]
One difference I am seeing with the script -- the replication is enabled via ASYNC mode, not sync. Some other key initialization configs on both the main and replica instance:
- "--isolation-level=READ_COMMITTED"
- "--replication-restore-state-on-startup=true"

Due to some internal configs I haven't been able to set up a minikube environment that can mimic our k8s setup. I am still seeing this issue on 2.22.0 however. Is it possible to try to replicate this in a real k8s environment instead? 

https://github.com/user-attachments/assets/09a8f74c-4736-4e64-9b71-21ca8ed9e0ec

**Comment by antejavor** [comment]
Hi @danielhsu93, I have managed to bring the main to an unresponsive state, after some time, the replica also got in the weird state. 

Here is the script below, it is not exactly what you are describing above, but it looks like some start: 
 

```
#!/bin/bash


# Check if minikube is running 
if ! minikube status > /dev/null 2>&1; then
  echo "Minikube is not running. Please start it using 'minikube start'."
  exit 1
fi

# Step 1: Install Memgraph using Helm, this os local helm, git pull the repo and add `clusterIP: None`  to the service.yaml file for run this as headless service.  
# ./helm-charts/charts/memgraph
helm install memgraph-db memgraph/memgraph --set replicaCount=2 \
                        --set service.enableWebsocketMonitoring=true \
                        --set service.websocketPortMonitoring=10000 \
                        --set "memgraphConfig[0]=--also-log-to-stderr=true" \
                        --set "memgraphConfig[1]=--log-level=TRACE" \
                        --set "memgraphConfig[2]=--replication-restore-state-on-startup=true" \
                        --set "memgraphConfig[3]=--isolation-level=READ_COMMITTED" \


# Check if the pods are running
while [[ $(kubectl get pods -l app.kubernetes.io/name=memgraph -o 'jsonpath={..status.phase}') != "Running Running" ]]; do
    echo "Waiting for pods to be in running status..."
    sleep 5
done

# Wait for all pods in the replica set to be in ready state
kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=memgraph --timeout=300s --all



# The check above are questionable, so we will add a sleep 30 to wait for the pods to be in running status.
# NAME            READY   STATUS    RESTARTS   AGE
# memgraph-db-0   1/1     Running   0          49s
# memgraph-db-1   1/1     Running   0          28s
# Pods need to be ready before we can proceed
sleep 30

# Get the pod names
MAIN_POD=$(kubectl get pods -l app.kubernetes.io/name=memgraph -o jsonpath='{.items[0].metadata.name}')
REPLICA_POD=$(kubectl get pods -l app.kubernetes.io/name=memgraph -o jsonpath='{.items[1].metadata.name}')

echo "Main pod: $MAIN_POD"
echo "Replica pod: $REPLICA_POD"


# Step 2: Set up the main and replica instances
kubectl exec -it $REPLICA_POD -c memgraph --  bash -c "echo 'SET REPLICATION ROLE TO REPLICA WITH PORT 10000;' | mgconsole"


# Show the replication role for both main and replica instances
kubectl exec -it $MAIN_POD -c memgraph -- bash -c "echo 'SHOW REPLICATION ROLE;' | mgconsole"
kubectl exec -it $REPLICA_POD -c memgraph -- bash -c "echo 'SHOW REPLICATION ROLE;' | mgconsole"


# Step 3: Register the replica using DNS
REPLICA_DNS=$(kubectl get pod $REPLICA_POD -o jsonpath='{.metadata.name}').memgraph-db.default.svc.cluster.local
echo "Replica DNS: $REPLICA_DNS"

REPLICA_IP=$(kubectl get pods -l app.kubernetes.io/name=memgraph -o jsonpath='{.items[1].status.podIP}')
echo "Replica IP: $REPLICA_IP"

kubectl exec -it $MAIN_POD -c memgraph -- bash -c "echo 'REGISTER REPLICA replica ASYNC TO \"$REPLICA_DNS:10000\";' | mgconsole"


# Show the replication status for the main instance
kubectl exec -it $MAIN_POD -c memgraph -- bash -c "echo 'SHOW REPLICAS;' | mgconsole"

# Continuously write data to the main instance
kubectl exec $MAIN_POD -c memgraph -- nohup bash -c "while true; do echo 'CREATE (n:Node {name: \"test\"});' | mgconsole; sleep 0.1; done" &

echo "Writing data to the main instance..."

# Wait for a few seconds before restarting the replica pod
sleep 5

echo "Restarting the replica pod..."
kubectl delete pod $REPLICA_POD

sleep 10

# Check if the pods are running
while [[ $(kubectl get pods -l app.kubernetes.io/name=memgraph -o 'jsonpath={..status.phase}') != "Running Running" ]]; do
    echo "Waiting for pods to be in running status..."
    sleep 5
done

# Wait for all pods in the replica set to be in ready state
kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=memgraph --timeout=300s --all


# Check the status of both main and replica pods
MAIN_POD=$(kubectl get pods -l app.kubernetes.io/name=memgraph -o jsonpath='{.items[0].metadata.name}')
REPLICA_POD=$(kubectl get pods -l app.kubernetes.io/name=memgraph -o jsonpath='{.items[1].metadata.name}')
MAIN_STATUS=$(kubectl get pod $MAIN_POD -o jsonpath='{.status.phase}')
REPLICA_STATUS=$(kubectl get pod $REPLICA_POD -o jsonpath='{.status.phase}')

echo "Main instance status: $MAIN_STATUS"
echo "Replica instance status: $REPLICA_STATUS"

# Get the node count from both main and replica instances
MAIN_NODE_COUNT=$(kubectl exec -it $MAIN_POD -c memgraph -- bash -c "echo 'MATCH (n) RETURN count(n);' | mgconsole") 
REPLICA_NODE_COUNT=$(kubectl exec -it $REPLICA_POD -c memgraph -- bash -c "echo 'MATCH (n) RETURN count(n);' | mgconsole")


echo "Main instance node count: $MAIN_NODE_COUNT"
echo "Replica instance node count: $REPLICA_NODE_COUNT"


# Display the last 100 lines of logs from both main and replica instances
echo "******** Logs from the main instance: ********"
kubectl logs $MAIN_POD --tail=100

echo "******** Logs from the replica instance: ********"
kubectl logs $REPLICA_POD --tail=100

# Wait for user input to proceed
read -p "Press Enter to continue..."


# Step 6: Clean up
helm uninstall memgraph-db
kubectl delete pvc --all
kubectl delete pv --all

```

**Comment by as51340** [comment]
The segfault doesn't occur anymore in 3.0.0.

These is values.yaml I used:
```
image:
  repository: memgraph/memgraph
  # Overrides the image tag whose default is v{{ .Chart.AppVersion }}
  tag:
  pullPolicy: IfNotPresent

## Override the default imagePullSecrets
useImagePullSecrets: false
imagePullSecrets:
- name: regcred

replicaCount: 2

## Node Affinity Preferred
# By setting theses parameters the PREFERRED deployment will be done first on the match LABELS with key and value then on other nodes.
# nodeKey: "nodegroup" give the name of a key
# Operator is In
# nodeValue: "memgraph" give the value of the key
affinity:
  nodeKey:
  nodeValue:


nodeSelector: {}

tolerations: []

service:
  ## ClusterIP, NodePort, LoadBalancer
  # ClusterIP keep the service inside the cluster makes it secure
  # NodePort would create a external port change port: between 30000-32767 accessible to all the nodes and Public IPs if not in a VPC
  # LoadBalancer is compabile with Cloud Providers on port: 80 without SSL redirected to the 7687
  type: ClusterIP

  # Bolt Port
  enableBolt: true
  boltPort: 7687  # NOTE: Make sure to change port in probes if you change this value.
  boltProtocol: TCP

  # Websocket Monitoring
  enableWebsocketMonitoring: true
  websocketPortMonitoring: 7444
  websocketPortMonitoringProtocol: TCP

  # HTTP Monitoring
  enableHttpMonitoring: false
  httpPortMonitoring: 9091
  httpPortMonitoringProtocol: http
  annotations: {}

persistentVolumeClaim:
  ## createStoragePVC `true` will create for each statefulset server a Persistant Volume Claim
  ## `false` will let you choose an existing Persistant Volume Claim or will create one with an existing volume
  createStorageClaim: true
  ## Using a Storage Class Name with policy `retain` will keep the Persistant Volume Claim and the Volume until you manually delete it
  ## If you use a Storage Class Name with policy `delete` the Persistant Volume Claim and Volume will be deleted when the helm release is deleted
  storageClassName:
  ## Storage Size must me at minimum 4x the maximum size of your Dataset for Snapshots
  ## See documentation for choosing the right size depending on the number of Snapshots you want to keep
  ## Default is 3 snapshots and you need space to create a new one and WAL files
  storageSize: 10Gi

  ## if `createStoragePVC` is `false` you can choose to use an existing Persistant Volume Claim
  ## Write the name and exising Persistant Volume Claim
  existingClaim: memgraph-0
  ## If you want to create a Persistant Volume Claim for an existing Volume
  storageVolumeName:

  ## Create a Persistant Volume Claim for Logs, if you use a Storage Class Name with policy `retain` the logs will be kept until you manually delete them
  # `false` will only write logs to stdout / stderr
  createLogStorage: true
  logStorageClassName:
  logStorageSize: 1Gi

  ## Create a Dynamic Persistant Volume Claim for Configs, Certificates (e.g. Bolt cert ) and rest of User related files
  createUserClaim: false
  userStorageClassName:
  userStorageSize: 1Gi
  userStorageAccessMode: "ReadWriteOnce"
  userMountPath:

# Default Storage Class for data and logs, defaults are for Minikube, make sure to change it for production deployments
# Examples provisioner: Minikube(k8s.io/minikube-hostpath) AWS (ebs.csi.aws.com), GCP (pd.csi.storage.gke.io), Azure (disk.csi.azure.com)
# Examples storageType: Minikube(hostPath) AWS (gp2), GCP (pd-standard), Azure (StandardSSD_LRS)

storageClass:
  create: false
  name: memgraph-generic-storage-class
  provisioner: "k8s.io/minikube-hostpath"
  storageType: "hostPath"
  fsType: ext4
  reclaimPolicy: Retain
  volumeBindingMode: Immediate

memgraphConfig:
- "--also-log-to-stderr=true"
- "--log-level=TRACE"
- "--isolation-level=READ_COMMITTED"
- "--replication-restore-state-on-startup=true"  # already defaulted to true

secrets:
  enabled: false
  name: memgraph-secrets
  userKey: USER
  passwordKey: PASSWORD

## Memgraph Enterprise Licence
# memgraphEnterpriseLicense: "<your-license>"
# memgraphOrganizationName: "<your-organization-name>"

memgraphEnterpriseLicense:
memgraphOrganizationName:

# Annotations to add to the statefulSet
statefulSetAnnotations: {}
# Annotations to add to the Pod
podAnnotations: {}

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

serviceAccount:
  # Specifies whether a service account should be created
  # If set to false and the name is provided, this service account must exist
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

container:
  terminationGracePeriodSeconds: 1800
  # When a container is ready to be used. Disabled until startupProbe succeeds.
  readinessProbe:
    tcpSocket:
      port: 7687
    failureThreshold: 20
    timeoutSeconds: 10
    periodSeconds: 5
  # To know when a container needs to be restarted.
  # Disabled until startupProbe succeeds.
  livenessProbe:
    tcpSocket:
      port: 7687
    failureThreshold: 20
    timeoutSeconds: 10
    periodSeconds: 5
  # When restoring Memgraph from a backup, it is important to give enough time app to start. Here, we set it to 2h by default.
  startupProbe:
    tcpSocket:
      port: 7687
    failureThreshold: 1440
    periodSeconds: 5

# List of custom query modules to be mounted into the app.
# These will be loaded automatically, on startup.
# Each module must be exposed by a ConfigMap under a specific file name.
customQueryModules: []

#   Must be an existing ConfigMap
# - volume: ""
#   Must be present in the ConfigMap referenced with `volume`
#   file: ""


# If you are experiencing issues with the sysctlInitContainer, you can disable it here.
# This is made to increase the max_map_count, necessary for high memory loads in Memgraph
# If you are experiencing crashing pod with the: Max virtual memory areas vm.max_map_count is too low
# you can increase the maxMapCount value.
sysctlInitContainer:
  enabled: true
  maxMapCount: 262144

```
helm install memgraph-db memgraph/memgraph -f values.yaml
