### ISSUE TITLE
Graph stream processing with Kafka

### ISSUE THREAD

**Issue by FuzzyStatic** [memgraph/memgraph#3039]
I followed the guide here https://memgraph.com/docs/data-streams/graph-stream-processing-with-kafka but when I go to test the stream I get 

```
Transformation failed
Kafka consumer movielens_stream check failed: timeout reached
```

Then I tried using my own Kafka instance and I get a similar result.

I'm doing this all through a docker-compose.yml file on MacOS ARM.

```yml
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  memgraph:
    image: memgraph/memgraph:latest
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      - MEMGRAPH_USER=memgraph
      - MEMGRAPH_PASSWORD=memgraph
      - MEMGRAPH="--log-level=TRACE"
    volumes:
      - ./kafka_transform.py:/usr/lib/memgraph/query_modules/kafka_transform.py

  memgraph-lab:
    image: memgraph/lab:latest
    ports:
      - "3000:3000"
    environment:
      - MEMGRAPH_HOST=memgraph
      - MEMGRAPH_PORT=7687
    depends_on:
      - memgraph
```

I'm not sure what to try next as the error is not descriptive. I'm not sure what is timing out. Is Memgraph not able to consume any data? Is the transformation stuff?

**Comment by antejavor** [comment]
Hi @FuzzyStatic, thanks for reporting this 🙇 , looks like the servers that are serving the [https://awesomedata.stream/](https://awesomedata.stream/) stopped working, will take a look at this on Monday. 

BTW., what are you trying to build?

**Comment by FuzzyStatic** [comment]
@antejavor thanks for the response, I hope the servers come back soon. Any idea why I still had issues even when I ran my own Kafka instance? Maybe I'm missing some required settings for Kafka and Memgraph to properly communicate?

I'm evaluating some different was to stream realtime data into Memgraph.

**Comment by FuzzyStatic** [comment]
I was able to get a local broker working, had to use a separate listener with the docker network service name for memgraph to talk to:

```yml
kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:29092:29092"
      - "127.0.0.1:9999:9999"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
```
